Feature/development
RokoVarano/NYT-clone pull request #4
Opened 2020-11-25 22:38 UTC by RokoVarano

This is our work so far. We closed the previous Pull request to fix some Lint errors.

2020-11-25 23:35 UTC, descholar-ceo requested changes
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @RokoVarano and @vicmaburrito  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your clone almost looks like the original page and it is really nice, congratulations on the good work you have done so far.
### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes]

- [ ] The links to your social networks should be clickable in your readme file
- [ ] Your readme file is missing the screenshot of your project, and live demo link
- [ ] Your readme file should follow the [microverse's readme template](https://raw.githubusercontent.com/microverseinc/readme-template/master/README.md)
- [ ] You should fix the linters errors before re-submitting for re-review :point_right: I looked at all of the lint errors you have, they are fixable, all you need is to sit and work on them until they are fixed
- [ ] Remove `.idea` folder from your repository, that is not related to this project but your IDE, so it's unprofessional to let unrelated files/folders in your repository :point_right: you can do that by following the below steps
```bash
git rm -rf .idea
git commit -am "Remove idea from the repo"
git push
```
- [ ] Your project is missing a big part, from `Suggested newsletters for you` to footer, that part should be worked on as well
- [ ] The `LOG IN` button in navbar has a stray less than `<` symbol, remove it.
- [ ] You used this `#titlepicks` which is an ID as a CSS selector, that is a bad practice, please use classes.
- [ ] CSS codes should be DRY (Don't Repeat Yourself), currently there are some properties which are being repeated several times in your CSS codes, example: `display: flex;` is repeated 10 times, this is bad and makes your code difficult to maintain. 

#### Advice: 
1. Whenever you see that you need to apply a specific property on different elements, create a specific class which hold that property, and then apply that class to whichever element you need,
2. Or you can just group those elements and apply that property at once,

- [ ] You have used inline styles from your html codes, that is a bad practice, please move all of the stylings in your CSS codes

- [ ] Using `flex` on this project is very good and encouraged since it is the main topic of it, but also we need you to learn and master how to use `float` and `grid`, currently there is no `grid` and no `float` in your CSS codes, try to use some
- [ ] You have commented codes in your HTML file, please remove them
- [ ] There is no `Editor's pick` aside section on the rightmost side of the page
- [ ] You should have used  [<aside> tag](https://www.w3schools.com/tags/tag_aside.asp) for Editor's picks section on the righmost side. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/aside_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
- [ ] The social media icons don't seem like the ones on the original page

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2020-11-26 01-18-28](https://user-images.githubusercontent.com/56886064/100291389-5306a680-2f86-11eb-8d7e-83fc44d5fdd9.png) | ![Screenshot from 2020-11-26 01-18-44](https://user-images.githubusercontent.com/56886064/100291410-5f8aff00-2f86-11eb-9c69-c1f936ce4bc2.png) |


:point_right: Could you see the difference :question: :question: :question: 

- [ ] Work again on this Pull request description, actually you should talk about the work you have done on it in summary,

- [ ] Implement all changes I suggested in inline comments in your codes

# [Optional changes]
- [ ] Your commit messages should be consistently in imperative mode or present tense, _i.e.:_ you should have written `Add more images of the article`  instead of writing `added more images of the article`, refer [to this article for more details on how to write a good && professional commit message](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

=======
If anything seems to be unclear to you, comment on this Pull Request and mention me as [@descholar-ceo](https://github.com/descholar-ceo)
 | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2020-11-25 23:35 UTC, descholar-ceo commented on README.md
> +- LinkedIn: https://www.linkedin.com/in/manuel-aldaraca
These social networks, should be written as links

2020-11-25 23:35 UTC, descholar-ceo commented on index.html
> +<!--    </div>-->
Leaving commented codes in your project is highly discouraged, please remove them

2020-11-27 02:41 UTC, RokoVarano commented
- Closing this pull request so linterns can be used again. Thanks for the advice!

2020-11-27 18:44 UTC, RokoVarano commented
Finished adding content to the project. The CSS Lint problems are due to it taking in the fontAwesome CSS files. We have added the directory into .gitignore, but it doesn't work. We are currently working to solve the issue.

- The Editor's Notes section to the right of the article has been added
- The footer of the article has been added
- The recommended newsletter section at the bottom of the article has been added
- The link menu at the very bottom of the website has been added.

2020-11-27 19:08 UTC, RokoVarano commented
Solved the FontAwesome issue

2020-11-27 19:20 UTC, ebeagusamuel requested changes
# Changes Required :recycle: 
Hello team :wave: 
You have done a nice job on this project. 
There are still some changes to be made.
- [ ] In the "More in Space and Astronomy" section, you should add more margin between the elements as it is in the original. Also, in the "Most popular" section try to make the font-weight be as close to those used in the original website in that section.
- [ ] Also, do not forget to fix the linter issues you have.

Once you have done all this, do go ahead and request another review.

slack(@ebeagusamuel)

2020-11-27 20:13 UTC, RokoVarano commented
- Suggested changes have been made.
- Lint reports no problems

2020-11-27 20:42 UTC, eypsrcnuygr approved these changes
## Status: Approved :partying_face: :tada: 
Hello team! Thanks for making the changes requested from the previous TSE. Your page looks amazing. :muscle: 
You have made all the mandatory requirements.
You can merge this branch and move on to the next project. :+1: 
Eyüp Sercan UYGUR

2020-11-27 20:45 UTC, merged